apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-echo-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: simple-echo-server
  template:
    metadata:
      labels:
        app: simple-echo-server
    spec:
      containers:
        -
          image: docker.io/matthewctoai/simple-echo-server:latest
          name: simple-echo-server
          ports:
            - containerPort: 8080
